feat: switch to buf and add CI steps (#14)
* feat: switch to buf and add CI steps

* fix: remove pb.go files from git

* fix: add missing ci attributes

* fix: add proto input folder to buf checks

* fix: make breaking change detector controlled by input

* fix: pin buf version on CI

* fix: use remote generation to simplify CI setup

* fix: make tidy script executable

* fix: dont fail tests if no tests triggered

diff --git a/.github/actions/bazel-command/action.yml b/.github/actions/bazel-command/action.yml
--- a/.github/actions/bazel-command/action.yml
+++ b/.github/actions/bazel-command/action.yml
@@ -23,13 +23,13 @@ runs:
         fetch-depth: 0
 
     - id: changed-files
-      if: ${{ inputs.affected_targets_only == 'true' }}
+      if: ${{ inputs.affected_targets_only }}
       uses: tj-actions/changed-files@v15
       with:
         separator: +
 
     - id: bazel-rdeps-query
-      if: ${{ inputs.affected_targets_only == 'true' }}
+      if: ${{ inputs.affected_targets_only}}
       shell: bash
       run: |
         echo "Query scope: '${{ inputs.scope }}'"
@@ -52,7 +52,15 @@ runs:
         if [[ "$targets" != "" ]]; then
           echo "Executing Bazel command:"
           echo "bazel $command $targets"
-          bazel $command $targets
+          bazel_return_code="0"
+          bazel $command $targets || bazel_return_code="$?"
+          if [[ "$bazel_return_code" == "4" && "$command" == "test" ]]; then
+            # Exit code 4 just means that there were no tests, so don't fail.
+            # https://docs.bazel.build/versions/4.2.2/guide.html#what-exit-code-will-i-get
+            exit 0
+          else
+            exit $bazel_return_code
+          fi
         else
           echo "Skipping Bazel $command; no targets in scope"
         fi
